/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as ApiPublicHooksResetDemoRouteImport } from './routes/api/public/hooks/reset-demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksResetDemoRoute = ApiPublicHooksResetDemoRouteImport.update({
  id: '/api/public/hooks/reset-demo',
  path: '/api/public/hooks/reset-demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/public/hooks/reset-demo': typeof ApiPublicHooksResetDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/public/hooks/reset-demo': typeof ApiPublicHooksResetDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/public/hooks/reset-demo': typeof ApiPublicHooksResetDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitemap/xml' | '/api/public/hooks/reset-demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap/xml' | '/api/public/hooks/reset-demo'
  id: '__root__' | '/' | '/sitemap/xml' | '/api/public/hooks/reset-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  ApiPublicHooksResetDemoRoute: typeof ApiPublicHooksResetDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reset-demo': {
      id: '/api/public/hooks/reset-demo'
      path: '/api/public/hooks/reset-demo'
      fullPath: '/api/public/hooks/reset-demo'
      preLoaderRoute: typeof ApiPublicHooksResetDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  ApiPublicHooksResetDemoRoute: ApiPublicHooksResetDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
